listener 1883 0.0.0.0
allow_anonymous false
persistence false

listener 8883 0.0.0.0
cafile /mosquitto/certs/ca.crt
certfile /mosquitto/certs/broker.crt
keyfile /mosquitto/certs/broker.key
require_certificate true
use_identity_as_username true
tls_version tlsv1.2
acl_file /mosquitto/config/acl
